### ISSUE TITLE
[Recording] Recording of walk-trough of 

### ISSUE THREAD

**Issue by dgomesbr** [dgomesbr/awesome-aws-workshops#30]
**Workshop**
[https://cicd.serverlessworkshops.io/](https://cicd.serverlessworkshops.io/?source=awesomeawsworkshops&utm_source=awesomeawsworkshops&utm_medium=github-issue)

**Tasks**

- [ ] Choose Language
- [ ] Record Section 0: SETUP
- [ ] Record Section 1: CREATE A NEW SAM APP
- [ ] Record Section 2: RUN PROJECT LOCALLY
- [ ] Record Section 3: MANUAL DEPLOY TO AWS
- [ ] Record Section 4: BUILD THE PIPELINE
- [ ] Record Section 5: CANARY DEPLOYMENTS
- [ ] Record Section 6: CLEANUP
- [ ] Video edit
- [ ] Publish
